// This file is auto-generated by @hey-api/openapi-ts

export const AccountDeleteResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'queued'
        },
        message: {
            type: 'string',
            title: 'Message',
            default: 'Account deletion queued. All data will be permanently removed within 60 seconds.'
        }
    },
    type: 'object',
    required: ['job_id'],
    title: 'AccountDeleteResponse'
} as const;

export const AdminStatsResponseSchema = {
    properties: {
        total_users: {
            type: 'integer',
            title: 'Total Users'
        },
        active_today: {
            type: 'integer',
            title: 'Active Today'
        },
        new_today: {
            type: 'integer',
            title: 'New Today'
        },
        pro_users: {
            type: 'integer',
            title: 'Pro Users'
        },
        daily_llm_spend_usd: {
            type: 'number',
            title: 'Daily Llm Spend Usd'
        },
        llm_spend_cap_usd: {
            type: 'number',
            title: 'Llm Spend Cap Usd'
        },
        sources_today: {
            type: 'integer',
            title: 'Sources Today'
        },
        metadocs_today: {
            type: 'integer',
            title: 'Metadocs Today'
        }
    },
    type: 'object',
    required: ['total_users', 'active_today', 'new_today', 'pro_users', 'daily_llm_spend_usd', 'llm_spend_cap_usd', 'sources_today', 'metadocs_today'],
    title: 'AdminStatsResponse'
} as const;

export const AdminTransactionOutSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        balance_after: {
            type: 'integer',
            title: 'Balance After'
        },
        operation: {
            type: 'string',
            title: 'Operation'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'amount', 'balance_after', 'operation', 'created_at'],
    title: 'AdminTransactionOut'
} as const;

export const AdminUserDetailResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        tier: {
            type: 'string',
            title: 'Tier'
        },
        credits_balance: {
            type: 'integer',
            title: 'Credits Balance'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        last_active_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Active At'
        },
        referral_code: {
            type: 'string',
            title: 'Referral Code'
        },
        recent_transactions: {
            items: {
                '$ref': '#/components/schemas/AdminTransactionOut'
            },
            type: 'array',
            title: 'Recent Transactions'
        },
        source_count: {
            type: 'integer',
            title: 'Source Count'
        }
    },
    type: 'object',
    required: ['id', 'email', 'display_name', 'tier', 'credits_balance', 'is_active', 'created_at', 'last_active_at', 'referral_code', 'recent_transactions', 'source_count'],
    title: 'AdminUserDetailResponse'
} as const;

export const AdminUserListResponseSchema = {
    properties: {
        users: {
            items: {
                '$ref': '#/components/schemas/AdminUserOut'
            },
            type: 'array',
            title: 'Users'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        }
    },
    type: 'object',
    required: ['users', 'total', 'page'],
    title: 'AdminUserListResponse'
} as const;

export const AdminUserOutSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        tier: {
            type: 'string',
            title: 'Tier'
        },
        credits_balance: {
            type: 'integer',
            title: 'Credits Balance'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        last_active_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Active At'
        }
    },
    type: 'object',
    required: ['id', 'email', 'display_name', 'tier', 'credits_balance', 'is_active', 'created_at', 'last_active_at'],
    title: 'AdminUserOut'
} as const;

export const BalanceResponseSchema = {
    properties: {
        balance: {
            type: 'integer',
            title: 'Balance'
        },
        transactions: {
            items: {
                '$ref': '#/components/schemas/CreditTransactionOut'
            },
            type: 'array',
            title: 'Transactions'
        }
    },
    type: 'object',
    required: ['balance', 'transactions'],
    title: 'BalanceResponse'
} as const;

export const Body_upload_file_v1_ingest_upload_postSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_file_v1_ingest_upload_post'
} as const;

export const ChatMessageRequestSchema = {
    properties: {
        message: {
            type: 'string',
            maxLength: 4000,
            minLength: 1,
            title: 'Message'
        },
        session_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Session Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ChatMessageRequest'
} as const;

export const ChatSessionDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        messages: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Messages'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        message_count: {
            type: 'integer',
            title: 'Message Count'
        }
    },
    type: 'object',
    required: ['id', 'title', 'messages', 'created_at', 'updated_at', 'message_count'],
    title: 'ChatSessionDetail'
} as const;

export const ChatSessionSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        message_count: {
            type: 'integer',
            title: 'Message Count'
        }
    },
    type: 'object',
    required: ['id', 'title', 'created_at', 'updated_at', 'message_count'],
    title: 'ChatSessionSummary'
} as const;

export const CheckoutSessionResponseSchema = {
    properties: {
        checkout_url: {
            type: 'string',
            title: 'Checkout Url'
        }
    },
    type: 'object',
    required: ['checkout_url'],
    title: 'CheckoutSessionResponse'
} as const;

export const ConflictResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        incumbent_content: {
            type: 'string',
            title: 'Incumbent Content'
        },
        challenger_content: {
            type: 'string',
            title: 'Challenger Content'
        },
        ai_classification: {
            type: 'string',
            title: 'Ai Classification'
        },
        ai_proposed_resolution: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Proposed Resolution'
        },
        confidence_score: {
            type: 'number',
            title: 'Confidence Score'
        },
        incumbent_source_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Incumbent Source Id'
        },
        challenger_source_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Challenger Source Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'incumbent_content', 'challenger_content', 'ai_classification', 'ai_proposed_resolution', 'confidence_score', 'incumbent_source_id', 'challenger_source_id', 'status', 'created_at'],
    title: 'ConflictResponse'
} as const;

export const CreateCheckoutSessionRequestSchema = {
    properties: {
        tier: {
            type: 'string',
            enum: ['pro', 'team'],
            title: 'Tier'
        },
        period: {
            type: 'string',
            enum: ['monthly', 'annual'],
            title: 'Period'
        }
    },
    type: 'object',
    required: ['tier', 'period'],
    title: 'CreateCheckoutSessionRequest'
} as const;

export const CreditAdjustRequestSchema = {
    properties: {
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['user_id', 'amount', 'reason'],
    title: 'CreditAdjustRequest'
} as const;

export const CreditAdjustResponseSchema = {
    properties: {
        new_balance: {
            type: 'integer',
            title: 'New Balance'
        },
        transaction_id: {
            type: 'integer',
            title: 'Transaction Id'
        }
    },
    type: 'object',
    required: ['new_balance', 'transaction_id'],
    title: 'CreditAdjustResponse'
} as const;

export const CreditTransactionOutSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        balance_after: {
            type: 'integer',
            title: 'Balance After'
        },
        operation: {
            type: 'string',
            title: 'Operation'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'amount', 'balance_after', 'operation', 'created_at'],
    title: 'CreditTransactionOut'
} as const;

export const GenerateRequestSchema = {
    properties: {
        prompt: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Prompt'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        }
    },
    type: 'object',
    required: ['prompt'],
    title: 'GenerateRequest'
} as const;

export const GenerateResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        estimated_credits: {
            type: 'integer',
            title: 'Estimated Credits'
        }
    },
    type: 'object',
    required: ['job_id', 'estimated_credits'],
    title: 'GenerateResponse'
} as const;

export const GraphEdgeSchema = {
    properties: {
        source: {
            type: 'string',
            title: 'Source'
        },
        target: {
            type: 'string',
            title: 'Target'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties',
            default: {}
        }
    },
    type: 'object',
    required: ['source', 'target', 'type'],
    title: 'GraphEdge'
} as const;

export const GraphMutationsSchema = {
    properties: {
        superseded_memory_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Superseded Memory Id'
        },
        active_memory_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Active Memory Id'
        },
        new_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'New Tags',
            default: []
        }
    },
    type: 'object',
    title: 'GraphMutations'
} as const;

export const GraphNodeSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        },
        memory_count: {
            type: 'integer',
            title: 'Memory Count',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'label', 'type', 'properties'],
    title: 'GraphNode'
} as const;

export const GraphQueryRequestSchema = {
    properties: {
        query: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Query'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        limit: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Limit',
            default: 20
        }
    },
    type: 'object',
    required: ['query'],
    title: 'GraphQueryRequest'
} as const;

export const GraphQueryResponseSchema = {
    properties: {
        cypher: {
            type: 'string',
            title: 'Cypher'
        },
        results: {
            '$ref': '#/components/schemas/GraphResponse'
        },
        explanation: {
            type: 'string',
            title: 'Explanation'
        },
        query_time_ms: {
            type: 'integer',
            title: 'Query Time Ms'
        }
    },
    type: 'object',
    required: ['cypher', 'results', 'explanation', 'query_time_ms'],
    title: 'GraphQueryResponse'
} as const;

export const GraphResponseSchema = {
    properties: {
        nodes: {
            items: {
                '$ref': '#/components/schemas/GraphNode'
            },
            type: 'array',
            title: 'Nodes'
        },
        edges: {
            items: {
                '$ref': '#/components/schemas/GraphEdge'
            },
            type: 'array',
            title: 'Edges'
        }
    },
    type: 'object',
    required: ['nodes', 'edges'],
    title: 'GraphResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImportPromptResponseSchema = {
    properties: {
        prompt_text: {
            type: 'string',
            title: 'Prompt Text'
        },
        detected_concepts: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Detected Concepts'
        }
    },
    type: 'object',
    required: ['prompt_text', 'detected_concepts'],
    title: 'ImportPromptResponse'
} as const;

export const MetaDocSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        original_prompt: {
            type: 'string',
            title: 'Original Prompt'
        },
        credits_consumed: {
            type: 'integer',
            title: 'Credits Consumed'
        },
        generated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Generated At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'original_prompt', 'credits_consumed', 'generated_at'],
    title: 'MetaDocSummary'
} as const;

export const ModelPreferenceUpdateSchema = {
    properties: {
        preferred_model: {
            type: 'string',
            title: 'Preferred Model'
        }
    },
    type: 'object',
    required: ['preferred_model'],
    title: 'ModelPreferenceUpdate'
} as const;

export const NotificationPreferencesUpdateSchema = {
    properties: {
        notify_welcome: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notify Welcome'
        },
        notify_low_credits: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notify Low Credits'
        },
        notify_ingestion_complete: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notify Ingestion Complete'
        }
    },
    type: 'object',
    title: 'NotificationPreferencesUpdate'
} as const;

export const PaginatedProfileResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/ProfileResponse'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page',
            default: 1
        },
        page_size: {
            type: 'integer',
            title: 'Page Size',
            default: 50
        },
        has_more: {
            type: 'boolean',
            title: 'Has More',
            default: false
        }
    },
    type: 'object',
    required: ['items', 'total'],
    title: 'PaginatedProfileResponse'
} as const;

export const PaginatedResponse_ChatSessionSummary_Schema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/ChatSessionSummary'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        has_more: {
            type: 'boolean',
            title: 'Has More'
        }
    },
    type: 'object',
    required: ['items', 'total', 'page', 'page_size', 'has_more'],
    title: 'PaginatedResponse[ChatSessionSummary]'
} as const;

export const PaginatedResponse_ConflictResponse_Schema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/ConflictResponse'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        has_more: {
            type: 'boolean',
            title: 'Has More'
        }
    },
    type: 'object',
    required: ['items', 'total', 'page', 'page_size', 'has_more'],
    title: 'PaginatedResponse[ConflictResponse]'
} as const;

export const PortalSessionResponseSchema = {
    properties: {
        portal_url: {
            type: 'string',
            title: 'Portal Url'
        }
    },
    type: 'object',
    required: ['portal_url'],
    title: 'PortalSessionResponse'
} as const;

export const ProfileCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ProfileCreate'
} as const;

export const ProfileResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'created_at'],
    title: 'ProfileResponse'
} as const;

export const ProfileUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        is_default: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Default'
        }
    },
    type: 'object',
    title: 'ProfileUpdate'
} as const;

export const ResolveActionSchema = {
    type: 'string',
    enum: ['ACCEPT_NEW', 'KEEP_OLD', 'CUSTOM'],
    title: 'ResolveAction'
} as const;

export const ResolveRequestSchema = {
    properties: {
        action: {
            '$ref': '#/components/schemas/ResolveAction'
        },
        custom_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Text'
        }
    },
    type: 'object',
    required: ['action'],
    title: 'ResolveRequest'
} as const;

export const ResolveResponseSchema = {
    properties: {
        conflict_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conflict Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        graph_mutations: {
            '$ref': '#/components/schemas/GraphMutations'
        }
    },
    type: 'object',
    required: ['conflict_id', 'status', 'graph_mutations'],
    title: 'ResolveResponse'
} as const;

export const TextIngestRequestSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags',
            default: []
        }
    },
    type: 'object',
    required: ['content'],
    title: 'TextIngestRequest'
} as const;

export const ToggleActiveRequestSchema = {
    properties: {
        active: {
            type: 'boolean',
            title: 'Active'
        }
    },
    type: 'object',
    required: ['active'],
    title: 'ToggleActiveRequest'
} as const;

export const ToggleActiveResponseSchema = {
    properties: {
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['is_active'],
    title: 'ToggleActiveResponse'
} as const;

export const UndoResponseSchema = {
    properties: {
        conflict_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conflict Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['conflict_id', 'status', 'message'],
    title: 'UndoResponse'
} as const;

export const UploadResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        source_id: {
            type: 'string',
            format: 'uuid',
            title: 'Source Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        duplicate: {
            type: 'boolean',
            title: 'Duplicate',
            default: false
        }
    },
    type: 'object',
    required: ['job_id', 'source_id', 'status'],
    title: 'UploadResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;