// This file is auto-generated by @hey-api/openapi-ts

export type AccountDeleteResponse = {
    job_id: string;
    status?: string;
    message?: string;
};

export type AdminStatsResponse = {
    total_users: number;
    active_today: number;
    new_today: number;
    pro_users: number;
    daily_llm_spend_usd: number;
    llm_spend_cap_usd: number;
    sources_today: number;
    metadocs_today: number;
};

export type AdminTransactionOut = {
    id: number;
    amount: number;
    balance_after: number;
    operation: string;
    created_at: string;
};

export type AdminUserDetailResponse = {
    id: string;
    email: string;
    display_name: (string | null);
    tier: string;
    credits_balance: number;
    is_active: boolean;
    created_at: string;
    last_active_at: (string | null);
    referral_code: string;
    recent_transactions: Array<AdminTransactionOut>;
    source_count: number;
};

export type AdminUserListResponse = {
    users: Array<AdminUserOut>;
    total: number;
    page: number;
};

export type AdminUserOut = {
    id: string;
    email: string;
    display_name: (string | null);
    tier: string;
    credits_balance: number;
    is_active: boolean;
    created_at: string;
    last_active_at: (string | null);
};

export type BalanceResponse = {
    balance: number;
    transactions: Array<CreditTransactionOut>;
};

export type Body_upload_file_v1_ingest_upload_post = {
    file: string;
};

export type ChatMessageRequest = {
    message: string;
    session_id?: (string | null);
    profile_id?: (string | null);
    model?: (string | null);
};

export type ChatSessionDetail = {
    id: string;
    title: (string | null);
    messages: Array<{
        [key: string]: unknown;
    }>;
    created_at: string;
    updated_at: string;
    message_count: number;
};

export type ChatSessionSummary = {
    id: string;
    title: (string | null);
    created_at: string;
    updated_at: string;
    message_count: number;
};

export type ConflictResponse = {
    id: string;
    incumbent_content: string;
    challenger_content: string;
    ai_classification: string;
    ai_proposed_resolution: (string | null);
    confidence_score: number;
    incumbent_source_id: (string | null);
    challenger_source_id: (string | null);
    status: string;
    created_at: string;
};

export type CreditAdjustRequest = {
    user_id: string;
    amount: number;
    reason: string;
};

export type CreditAdjustResponse = {
    new_balance: number;
    transaction_id: number;
};

export type CreditTransactionOut = {
    id: number;
    amount: number;
    balance_after: number;
    operation: string;
    created_at: string;
};

export type GenerateRequest = {
    prompt: string;
    profile_id?: (string | null);
    model?: (string | null);
};

export type GenerateResponse = {
    job_id: string;
    estimated_credits: number;
};

export type GraphEdge = {
    source: string;
    target: string;
    type: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type GraphMutations = {
    superseded_memory_id?: (string | null);
    active_memory_id?: (string | null);
    new_tags?: Array<(string)>;
};

export type GraphNode = {
    id: string;
    label: string;
    type: string;
    properties: {
        [key: string]: unknown;
    };
    memory_count?: number;
};

export type GraphQueryRequest = {
    query: string;
    profile_id?: (string | null);
    limit?: number;
};

export type GraphQueryResponse = {
    cypher: string;
    results: GraphResponse;
    explanation: string;
    query_time_ms: number;
};

export type GraphResponse = {
    nodes: Array<GraphNode>;
    edges: Array<GraphEdge>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImportPromptResponse = {
    prompt_text: string;
    detected_concepts: Array<(string)>;
};

export type ModelPreferenceUpdate = {
    preferred_model: string;
};

export type NotificationPreferencesUpdate = {
    notify_welcome?: (boolean | null);
    notify_low_credits?: (boolean | null);
    notify_ingestion_complete?: (boolean | null);
};

export type PaginatedProfileResponse = {
    items: Array<ProfileResponse>;
    total: number;
    page?: number;
    page_size?: number;
    has_more?: boolean;
};

export type PaginatedResponse_ChatSessionSummary_ = {
    items: Array<ChatSessionSummary>;
    total: number;
    page: number;
    page_size: number;
    has_more: boolean;
};

export type PaginatedResponse_ConflictResponse_ = {
    items: Array<ConflictResponse>;
    total: number;
    page: number;
    page_size: number;
    has_more: boolean;
};

export type ProfileCreate = {
    name: string;
    description?: (string | null);
    icon?: (string | null);
    color?: (string | null);
    is_default?: boolean;
};

export type ProfileResponse = {
    id: string;
    name: string;
    description?: (string | null);
    icon?: (string | null);
    color?: (string | null);
    is_default?: boolean;
    created_at: string;
};

export type ProfileUpdate = {
    name?: (string | null);
    description?: (string | null);
    icon?: (string | null);
    color?: (string | null);
    is_default?: (boolean | null);
};

export type ResolveAction = 'ACCEPT_NEW' | 'KEEP_OLD' | 'CUSTOM';

export type ResolveRequest = {
    action: ResolveAction;
    custom_text?: (string | null);
};

export type ResolveResponse = {
    conflict_id: string;
    status: string;
    graph_mutations: GraphMutations;
};

export type TextIngestRequest = {
    content: string;
    profile_id?: (string | null);
    tags?: Array<(string)>;
};

export type ToggleActiveRequest = {
    active: boolean;
};

export type ToggleActiveResponse = {
    is_active: boolean;
};

export type UndoResponse = {
    conflict_id: string;
    status: string;
    message: string;
};

export type UploadResponse = {
    job_id: string;
    source_id: string;
    status: string;
    duplicate?: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckHealthGetResponse = ({
    [key: string]: unknown;
});

export type ListUsersV1AdminUsersGetData = {
    authorization?: (string | null);
    page?: number;
    pageSize?: number;
    /**
     * Email search (case-insensitive)
     */
    q?: (string | null);
};

export type ListUsersV1AdminUsersGetResponse = (AdminUserListResponse);

export type GetUserDetailV1AdminUsersUserIdGetData = {
    authorization?: (string | null);
    userId: string;
};

export type GetUserDetailV1AdminUsersUserIdGetResponse = (AdminUserDetailResponse);

export type AdjustCreditsV1AdminCreditsAdjustPostData = {
    authorization?: (string | null);
    requestBody: CreditAdjustRequest;
};

export type AdjustCreditsV1AdminCreditsAdjustPostResponse = (CreditAdjustResponse);

export type ToggleActiveV1AdminUsersUserIdToggleActivePostData = {
    authorization?: (string | null);
    requestBody: ToggleActiveRequest;
    userId: string;
};

export type ToggleActiveV1AdminUsersUserIdToggleActivePostResponse = (ToggleActiveResponse);

export type GetAdminStatsV1AdminStatsGetData = {
    authorization?: (string | null);
};

export type GetAdminStatsV1AdminStatsGetResponse = (AdminStatsResponse);

export type UploadFileV1IngestUploadPostData = {
    authorization?: (string | null);
    formData: Body_upload_file_v1_ingest_upload_post;
};

export type UploadFileV1IngestUploadPostResponse = (UploadResponse);

export type IngestTextV1IngestTextPostData = {
    authorization?: (string | null);
    requestBody: TextIngestRequest;
};

export type IngestTextV1IngestTextPostResponse = (UploadResponse);

export type StreamProgressV1IngestStreamSourceIdGetData = {
    sourceId: string;
    token?: (string | null);
};

export type StreamProgressV1IngestStreamSourceIdGetResponse = (unknown);

export type GetImportPromptV1IngestImportPromptGetData = {
    authorization?: (string | null);
    profileId?: (string | null);
};

export type GetImportPromptV1IngestImportPromptGetResponse = (ImportPromptResponse);

export type GetGraphNodesV1GraphNodesGetData = {
    authorization?: (string | null);
    limit?: number;
    /**
     * Comma-separated node types, e.g. Concept,Memory
     */
    nodeTypes?: (string | null);
    profileId?: (string | null);
};

export type GetGraphNodesV1GraphNodesGetResponse = (GraphResponse);

export type GetGraphNeighborhoodV1GraphNeighborhoodNodeIdGetData = {
    authorization?: (string | null);
    hops?: number;
    limit?: number;
    nodeId: string;
};

export type GetGraphNeighborhoodV1GraphNeighborhoodNodeIdGetResponse = (GraphResponse);

export type NaturalLanguageGraphQueryV1GraphQueryPostData = {
    authorization?: (string | null);
    requestBody: GraphQueryRequest;
};

export type NaturalLanguageGraphQueryV1GraphQueryPostResponse = (GraphQueryResponse);

export type ListConflictsV1ConflictsGetData = {
    authorization?: (string | null);
    page?: number;
    pageSize?: number;
    status?: (string | null);
};

export type ListConflictsV1ConflictsGetResponse = (PaginatedResponse_ConflictResponse_);

export type ResolveConflictV1ConflictsConflictIdResolvePostData = {
    authorization?: (string | null);
    conflictId: string;
    requestBody: ResolveRequest;
};

export type ResolveConflictV1ConflictsConflictIdResolvePostResponse = (ResolveResponse);

export type UndoResolutionV1ConflictsConflictIdUndoPostData = {
    authorization?: (string | null);
    conflictId: string;
};

export type UndoResolutionV1ConflictsConflictIdUndoPostResponse = (UndoResponse);

export type GenerateMetaDocumentV1MetadocGeneratePostData = {
    authorization?: (string | null);
    requestBody: GenerateRequest;
};

export type GenerateMetaDocumentV1MetadocGeneratePostResponse = (GenerateResponse);

export type StreamMetaDocumentV1MetadocStreamJobIdGetData = {
    jobId: string;
    token?: (string | null);
};

export type StreamMetaDocumentV1MetadocStreamJobIdGetResponse = (unknown);

export type GetCreditsBalanceV1CreditsBalanceGetData = {
    authorization?: (string | null);
};

export type GetCreditsBalanceV1CreditsBalanceGetResponse = (BalanceResponse);

export type ClerkWebhookWebhooksClerkPostResponse = ({
    [key: string]: unknown;
});

export type StripeWebhookWebhooksStripePostResponse = ({
    [key: string]: unknown;
});

export type DeleteAccountV1AccountDeleteData = {
    authorization?: (string | null);
};

export type DeleteAccountV1AccountDeleteResponse = (AccountDeleteResponse);

export type UpdateModelPreferenceV1AccountModelPreferencePatchData = {
    authorization?: (string | null);
    requestBody: ModelPreferenceUpdate;
};

export type UpdateModelPreferenceV1AccountModelPreferencePatchResponse = ({
    [key: string]: unknown;
});

export type UpdateNotificationPreferencesV1AccountNotificationPreferencesPatchData = {
    authorization?: (string | null);
    requestBody: NotificationPreferencesUpdate;
};

export type UpdateNotificationPreferencesV1AccountNotificationPreferencesPatchResponse = ({
    [key: string]: unknown;
});

export type SendMessageV1ChatMessagePostData = {
    authorization?: (string | null);
    requestBody: ChatMessageRequest;
};

export type SendMessageV1ChatMessagePostResponse = (unknown);

export type ListSessionsV1ChatSessionsGetData = {
    authorization?: (string | null);
    page?: number;
    pageSize?: number;
};

export type ListSessionsV1ChatSessionsGetResponse = (PaginatedResponse_ChatSessionSummary_);

export type GetSessionV1ChatSessionsSessionIdGetData = {
    authorization?: (string | null);
    sessionId: string;
};

export type GetSessionV1ChatSessionsSessionIdGetResponse = (ChatSessionDetail);

export type DeleteSessionV1ChatSessionsSessionIdDeleteData = {
    authorization?: (string | null);
    sessionId: string;
};

export type DeleteSessionV1ChatSessionsSessionIdDeleteResponse = (void);

export type ListProfilesV1ProfilesGetData = {
    authorization?: (string | null);
};

export type ListProfilesV1ProfilesGetResponse = (PaginatedProfileResponse);

export type CreateProfileV1ProfilesPostData = {
    authorization?: (string | null);
    requestBody: ProfileCreate;
};

export type CreateProfileV1ProfilesPostResponse = (ProfileResponse);

export type UpdateProfileV1ProfilesProfileIdPatchData = {
    authorization?: (string | null);
    profileId: string;
    requestBody: ProfileUpdate;
};

export type UpdateProfileV1ProfilesProfileIdPatchResponse = (ProfileResponse);

export type DeleteProfileV1ProfilesProfileIdDeleteData = {
    authorization?: (string | null);
    profileId: string;
};

export type DeleteProfileV1ProfilesProfileIdDeleteResponse = (void);